services:
  web_115_302:
    build: .
    image: chenyanggao/web_115_302
    container_name: web_115_302
    ports:
      - "8000:80"
    networks:
      - local
    volumes:
      - "~/web_115_302:/etc/web_115_302"
    restart: always
    stdin_open: true
    tty: true
    command: ["/app/__main__.py", "--cookies-path", "115-cookies.txt", "--login-app", "${LOGIN_APP}", "--cookies", "${COOKIES}"]

networks:
  local:
    driver: bridge
